import { Result, ok, err, tryAsync } from "../utils/result";
import { OpenRouterError, ConfigError } from "../utils/errors";
import { ConfigService } from "./ConfigService";
import { join } from "path";
import { IncrementalLogService } from "./IncrementalLogService";

export class OpenRouterService {
  static async generate(prompt: string, modelOverride?: string): Promise<Result<string, OpenRouterError | ConfigError>> {
    const configResult = await ConfigService.load();
    if (!configResult.ok) {
      const error = new ConfigError(`Falha ao ler configuração para OpenRouter: ${configResult.error.message}`);
      IncrementalLogService.error(error, 'OpenRouterService.generate');
      return err(error);
    }
    const config = configResult.value;
    if (!config.apiKey) {
      const error = new ConfigError("API Key não configurada. Configure nas Configurações.");
      IncrementalLogService.error(error, 'OpenRouterService.generate');
      return err(error);
    }

    let defaultModel = "google/gemini-2.5-flash";
    try {
      const menusFile = Bun.file(join(process.cwd(), "config", "menus.json"));
      if (await menusFile.exists()) {
        const menusData = await menusFile.json();
        if (menusData.defaultModel) {
          defaultModel = menusData.defaultModel;
        }
      }
    } catch (e) {
      // Falha silenciosa para leitura de fallback
    }

    const modelName = modelOverride || config.model || defaultModel;

    const bodyPayload = {
      model: modelName,
      messages: [
        { role: "user", content: prompt }
      ]
    };
    
    IncrementalLogService.apiRequest('OpenRouterService.generate', 'POST', 'https://openrouter.ai/api/v1/chat/completions', {
      model: modelName,
      messageLength: prompt.length,
    });

    const result = await tryAsync(async () => {
      const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${config.apiKey}`,
          "HTTP-Referer": "http://localhost:3000", // Optional, for OpenRouter rankings
          "X-Title": "Replication TUI", // Optional, for OpenRouter rankings
          "Content-Type": "application/json"
        },
        body: JSON.stringify(bodyPayload)
      });

      if (!response.ok) {
        const errorText = await response.text();
        IncrementalLogService.apiResponse('OpenRouterService.generate', response.status, {
          error: errorText,
        });
        throw new Error(`OpenRouter API error (${response.status}): ${errorText}`);
      }

      const data = await response.json();
      IncrementalLogService.apiResponse('OpenRouterService.generate', response.status, {
        choices: data.choices?.length || 0,
        usage: data.usage,
      });

      if (!data.choices || data.choices.length === 0) {
        const errorStr = "No response generated by OpenRouter";
        const error = new OpenRouterError(errorStr);
        IncrementalLogService.error(error, 'OpenRouterService.generate');
        throw error;
      }

      return data.choices[0].message.content;
    }, "OpenRouterService.generate");

    if (!result.ok) {
      const error = new OpenRouterError(result.error.message);
      IncrementalLogService.error(error, 'OpenRouterService.generate');
      return err(error);
    }

    return ok(result.value);
  }

  static async enhanceInstruction(instruction: string): Promise<Result<string, OpenRouterError | ConfigError>> {
    const prompt = `Melhore a seguinte instrução para um prompt de IA. Torne-a mais clara, direta e detalhada, preservando o objetivo original. Retorne APENAS a instrução melhorada. Instrução original: ${instruction}`;
    return this.generate(prompt);
  }
}