import { Result, ok, err, tryAsync } from "../utils/result";
import { OpenRouterError, ConfigError } from "../utils/errors";
import { ConfigService } from "./ConfigService";

export class OpenRouterService {
  static async generate(prompt: string, modelOverride?: string): Promise<Result<string, OpenRouterError | ConfigError>> {
    const configResult = await ConfigService.load();
    if (!configResult.ok) {
      return err(new ConfigError(`Falha ao ler configuração para OpenRouter: ${configResult.error.message}`));
    }
    const config = configResult.value;
    if (!config.apiKey) {
      return err(new ConfigError("API Key não configurada. Configure nas Configurações."));
    }

    const modelName = modelOverride || config.model || "google/gemini-2.5-flash";

    const result = await tryAsync(async () => {
      const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${config.apiKey}`,
          "HTTP-Referer": "http://localhost:3000", // Optional, for OpenRouter rankings
          "X-Title": "Replication TUI", // Optional, for OpenRouter rankings
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: modelName,
          messages: [
            { role: "user", content: prompt }
          ]
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenRouter API error (${response.status}): ${errorText}`);
      }

      const data = await response.json();
      if (!data.choices || data.choices.length === 0) {
        throw new Error("No response generated by OpenRouter");
      }
      
      return data.choices[0].message.content;
    }, "OpenRouterService.generate");

    if (!result.ok) {
      return err(new OpenRouterError(result.error.message));
    }

    return ok(result.value);
  }

  static async enhanceInstruction(instruction: string): Promise<Result<string, OpenRouterError | ConfigError>> {
    const prompt = `Melhore a seguinte instrução para um prompt de IA. Torne-a mais clara, direta e detalhada, preservando o objetivo original. Retorne APENAS a instrução melhorada. Instrução original: ${instruction}`;
    return this.generate(prompt);
  }
}